name: "Component"
description: "Document of a component"
title: "[Component]: "
labels: ["component", "frontend", "documentation"]
body:
  - type: textarea
    id: Description
    attributes:
      label: "Describe the component"
    validations:
      required: true