name: Deploy GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the review site
      - name: Build TEL Frontend review site
        run: node packages/tel-frontend-review/build.mjs

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: packages/tel-frontend-review/dist
